### ISSUE TITLE
Password is hardcoded in store_test.go

### ISSUE THREAD

**Issue by tylerezimmerman** [thycotic/dsv-cli#10]
https://github.com/thycotic/dsv-cli/blob/master/store/store_test.go

Password is hardcoded in store_test.go

![image](https://user-images.githubusercontent.com/100804646/191780822-50d21115-af1c-4708-961f-1143299f8332.png)

**Comment by sheldonhull** [comment]
This is a valid use as it's a unit test performing validation of the behavior of store.
Not a vulnerability and used for unit testing the application. Good catch but marking as a false positive.
