### ISSUE TITLE
Password is hardcoded in integration_test.go

### ISSUE THREAD

**Issue by tylerezimmerman** [thycotic/dsv-cli#11]
Password is hardcoded in integration_test.go

https://github.com/thycotic/dsv-cli/blob/master/cicd-integration/integration_test.go

![image](https://user-images.githubusercontent.com/100804646/191781116-30f40796-48b3-4418-9e62-7f88eda28c28.png)

**Comment by sheldonhull** [comment]
This is a valid use as it's a sequence of actions that the test runs and discards.
In this scenario the value makes sense to hard coded for just running through a sequence of testings to confirm behavior is functional.
