### ISSUE TITLE
DSV network requests are extremely slow on M1 Macs

### ISSUE THREAD

**Issue by maxsokolovsky** [thycotic/dsv-cli#16]
I saw that on two different M1 Macs, any network request DSV makes takes exactly 10.3 seconds. Whether DSV checks for a possible update, or fetches a secret, or looks up a tenant name, it always takes just over ten seconds. I believe I noticed this on version 1.38. The latest 1.39 still has this behavior.

On Linux x64, everything is fine - still on the same network, even in a container.

**Comment by sheldonhull** [comment]
@maxsokolovsky working on getting dsv-cli migrated to this new repo with the publishing process. Feel free to ping here if you don't see any updates within the next 2 weeks. I'd be glad to try and investigate further once I'm done with this other work. Cheers

**Comment by sheldonhull** [comment]
Asking for someone to look into this in the meantime @maxsokolovsky so we get a little further on this. Thanks for your patience!

**Comment by maxsokolovsky** [comment]
Hi @sheldonhull, sorry, I think this is a false alarm. The problem is likely with my local network. Having timeouts or long waits with other things as well, such as when pulling images from Docker Hub. When I run dsv commands while on VPN or Personal Hotspot instead of my Wi-Fi, the latency is normal.

This is something with my network, although I haven't been able to figure out - tried resetting the router, flushing local DNS cache, edited `/etc/resolve.conf`and so on - to no avail. But this isn't a problem with dsv. Not sure why I have problems with only some commands/services...

**Comment by sheldonhull** [comment]
> Hi @sheldonhull, sorry, I think this is a false alarm. The problem is likely with my local network. Having timeouts or long waits with other things as well, such as when pulling images from Docker Hub. When I run dsv commands while on VPN or Personal Hotspot instead of my Wi-Fi, the latency is normal.
> 
> This is something with my network, although I haven't been able to figure out - tried resetting the router, flushing local DNS cache, edited `/etc/resolve.conf`and so on - to no avail. But this isn't a problem with dsv. Not sure why I have problems with only some commands/services...

@maxsokolovsky cool.  Sorry to hear that. Hate dealing with those type of issues. 
I use Little Snitch on Mac. Might look at that and filter to dsv and then see what's different. Free trial I think. Shows the map of where the calls are going and you could compare and see if any difference in what it's hitting. I'll close for now but by all means ads a comment if you figure out what happened or reopen if she's related to  DSV infra. 👍
