### ISSUE TITLE
Add a macOS arm64 build

### ISSUE THREAD

**Issue by maxsokolovsky** [thycotic/dsv-cli#5]
Would be great to be able to keep using `dsv` on macOS running on Apple M1 CPU.
I can submit a PR, let me know, friends!

**Comment by andrii-zakurenyi** [comment]
Hi @maxsokolovsky 
Thanks for not forgetting about us :)

Yes, thank you, we are planning to add support for M1 since it will be so easy to do because of Go :technologist: 

btw, you can create more issues here, I'm subscribed now and will be able to answer more quickly. Sorry for the delay

**Comment by andrii-zakurenyi** [comment]
wow, one month delay...

**Comment by maxsokolovsky** [comment]
Thanks for adding this, works great!
