### ISSUE TITLE
The binary is not signed for macOS

### ISSUE THREAD

**Issue by maxsokolovsky** [thycotic/dsv-cli#6]
The dsv binary appears to be unsigned – macOS x86 refuses to run it, unless I override in Security & Privacy. It says the binary is from an unidentified developer.

**Comment by tdillenbeck** [comment]
Hey Max!  I love that you are looking in on things here.  I just checked on my Mac, and the releases here on Github and the downloads page are the same binary, and it is signed.  I do have to approve it the first time after downloading it, which is a pain, but once it's been approved, the next version works well.  I installed a tool called WhatsYourSign that shows the details of signing, and it checked out.  Now, you say x86, but I expect you mean x64, unless you are running on a very old MacOS. 
![Screen Shot 2022-04-11 at 2 21 39 PM](https://user-images.githubusercontent.com/21064520/162830389-34adffc1-416c-4754-9d2e-e43d2ca353c0.png)

**Comment by maxsokolovsky** [comment]
Hi Thomas, thanks for the response! What's strange is that I have to approve every new version of dsv, and I've been running macOS Monterey for a while now. Each new version is a completely different binary, could this be the reason?

**Comment by tdillenbeck** [comment]
Ok, on further inspection, it looks like the 1.30 and 1.31 weren't signed.  But 1.32 is.  Versions 1.28 and 1.29 are signed.  So there was a lapse in something, perhaps our signing cert lapsed.  I will add a test to verify that new builds are signed in the future.  Thanks for alerting me on this!
