### ISSUE TITLE
CLI update notification not working

### ISSUE THREAD

**Issue by maxsokolovsky** [thycotic/dsv-cli#7]
The CLI is not notifying about the availability of a new version. After the `1.32.0` release, it checked for an update and specified in the cache that the latest existing version is `1.31.0`. 
Three days later, dsv fetched the update info again and got the same latest version, which is the previous one.

**Comment by andrii-zakurenyi** [comment]
Hi! Thanks for your report. Looks like migration problems related to a new place from which you can download the cli.
Previously it was: https://dsv.thycotic.com/downloads/
And now it is: https://dsv.secretsvaultcloud.com/downloads/

We will come up with solution how to update it properly soon. BTW PR that adds ARM64 builds is on review

**Comment by sheldonhull** [comment]
Closing for now. We'll have brew installation possible shortly.
In addition, you can install via curl or aquaproj as well. 

Quick snippet for curl based update: 

```shell
version=$(curl -sb -H "Accept: application/json" https://s3.amazonaws.com/dsv.secretsvaultcloud.com/cli-version.json | $(go env GOPATH)/bin/yq '.latest')
echo "version: $version"
curl -fSsl https://dsv.secretsvaultcloud.com/downloads/cli/$version/dsv-darwin-x64 -o dsv && chmod +x ./dsv && sudo mv ./dsv /usr/local/bin
```

I've been using aquaproj as a great alternative.
If you still want this open, feel free to reopen.
The github releases, uploads, and all should be updated soon now that it's migrated over to DelineaXPM/dsv-cli location.
